### ISSUE TITLE
per container theme?

### ISSUE THREAD

**Issue by zahachtah** [josefaidt/svelte-themer#7]
This is super useful!

I have a very special case where I might want to theme within containers. Do you know if it's possible to add a container flag such as

```css
.container > :global(svg)
```

I am not sure how one would inject the `.container > :global ` part...

The exampIe got this from is here:

https://svelte.dev/repl/4e04a629ab934863b09c4ee3f69d99a1?version=3.8.1

I'll try to check out your code to see if I can solve it but if you have a quick idea how to do it I'd appreciate it!!

Cheers, /Jon

**Comment by josefaidt** [comment]
Hi @zahachtah apologies for the delay! I do have theme classes set up, however they only apply to the `html` tag. Let me see if I can back this out to create the theme utility classes. This should overwrite the theme CSS vars

**Comment by josefaidt** [comment]
Hi @zahachtah this is now possible through the use of adding a theme class such as `theme--dark` or `theme--light` to apply the new CSS variables. The only caveat being the color properties will have to be set on the component in order to consume the updated CSS variables. 

https://codesandbox.io/s/musing-moon-7uvyi?file=/Box.svelte
